// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhnheusptjkppwobqgep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRobmhldXNwdGprcHB3b2JxZ2VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NTcwMDUsImV4cCI6MjA2NjUzMzAwNX0.E6rMTva2CBqTpIMKog4H6_BDBcvHG-TxcT3F2NxS228";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);